name: tcCombatLog
main: com.tcoded.tccombatlog.TcCombatLog
version: 1.0
api-version: "1.21"
depend: [WorldGuard]

commands:
  tccombatlog:
    permission: "tccombatlog.command.tccombatlog"
    aliases: [combatlog, combat, tccl, tcl]