name: tcCombatLog
main: com.tcoded.tccombatlog.TcCombatLog
version: "${version}"
api-version: "1.21"
depend: [WorldGuard]

commands:
  tccombatlog:
    permission: "tccombatlog.command.tccombatlog"
    aliases: [combatlog, combat, tccl, tcl]

permissions:
  tccombatlog.bypass.combat:
    description: "Prevents the player from being placed into combat. Attacking players are still tagged."
    default: false
  tccombatlog.bypass.command:
    description: "Allows running any commands while in combat."
    default: false